services:
  app:
    restart: always
    container_name: gugik2osm-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "45000:80"
    volumes:
      - ./app:/opt/gugik2osm/app
      - ./web:/opt/gugik2osm/web
      - ./processing:/opt/gugik2osm/git/processing
      - ./log:/opt/gugik2osm/log
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      - PGDATABASE=gugik2osm
      - PGHOSTADDR=172.31.0.2
      - PGPORT=25432
      - PGUSER=postgres
      - PGUSER_RO=postgres
      - PGPASSWORD=1234
      - PGPASSWORD_RO=1234
      - TERYTUSER=''
      - TERYTPASSWORD=''
    networks:
      - gugik2osm
  db:
    container_name: gugik2osm-db
    image: kartoza/postgis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=1234
      - POSTGRES_DBNAME=gis
      - MAINTENANCE_WORK_MEM=512MB
    ports:
      - "25432:5432"
    shm_size: '4gb'
    volumes:
      - ./setup-db.sql:/docker-entrypoint-initdb.d/setup-db.sql
    networks:
      - gugik2osm
networks:
  gugik2osm:
    driver: bridge